name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI
    - name: Install playwright
      run: playwright install
    - name: Test
      run: dotnet test ${GITHUB_WORKSPACE}/CaducaRest.PlayWright.UITest/*.csproj --logger "html;logfilename=testResults.html"
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{ github.workspace }}/CaducaRest.PlayWright.UITest/TestResults/testResults.html
    - name: Test
      run: dotnet test ${GITHUB_WORKSPACE}/CaducaRest.PlayWright.UITest/*.csproj --logger "html;logfilename=testResults.html"
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{ github.workspace }}/CaducaRest.PlayWright.UITest/TestResults/testResults.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/CaducaRest.PlayWright.UITest/TestResults/
